image:
    file: .gitpod.dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
    - init: /usr/bin/python3 path_finding.py
      command: /usr/bin/python3 path_finding.py
